"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv
import dj_database_url


# ============================================================
# BASE DIR
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

# En local, Django charge les variables depuis .env
# Sur Railway, les variables sont fournies directement
# par l'environnement Railway.
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


# ============================================================
# ALLOWED HOSTS
# ============================================================

railway_hostname = os.environ.get("RAILWAY_PUBLIC_DOMAIN")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

if railway_hostname:
    ALLOWED_HOSTS.append(railway_hostname)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Applications du projet
    "users",
    "chatbot",
    "courses",

    # API
    "rest_framework",
    "rest_framework_simplejwt",

    # CORS
    "corsheaders",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Fichiers statiques
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # CORS
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# CORS
# ============================================================

# En développement local :
# React peut communiquer librement avec Django.
#
# En production :
# nous définirons FRONTEND_URL sur Railway.

CORS_ALLOW_ALL_ORIGINS = DEBUG

frontend_url = os.environ.get("FRONTEND_URL")

if frontend_url:
    CORS_ALLOWED_ORIGINS = [
        frontend_url,
    ]
else:
    CORS_ALLOWED_ORIGINS = []


# ============================================================
# CSRF
# ============================================================
CSRF_TRUSTED_ORIGINS = []

if frontend_url:
    CSRF_TRUSTED_ORIGINS.append(frontend_url)

if railway_hostname:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{railway_hostname}"
    )


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "backend.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "backend.wsgi.application"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# ============================================================
# JWT
# ============================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}


# ============================================================
# DATABASE
# ============================================================

# Railway fournit DATABASE_URL automatiquement lorsqu'un
# PostgreSQL Railway est connecté au service Django.
#
# En local, on continue d'utiliser les variables de ton .env :
#
# DB_NAME
# DB_USER
# DB_PASSWORD
# DB_HOST
# DB_PORT

print("DATABASE_URL présente :", bool(os.environ.get("DATABASE_URL")))

DATABASES = {
    "default": dj_database_url.parse(
        os.environ["DATABASE_URL"],
        conn_max_age=600,
        ssl_require=True,
    )
}
# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# GEMINI API
# ============================================================

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")


# ============================================================
# CHROMADB / RAG
# ============================================================

# En local :
#     backend/chroma_db
#
# Sur Railway :
#     le chemin sera fourni par CHROMA_DB_PATH
#     et pointera vers notre volume persistant.

CHROMA_DB_PATH = os.environ.get(
    "CHROMA_DB_PATH",
    str(BASE_DIR / "chroma_db"),
)


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"