# Generated by Django 6.0.4 on 2026-04-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
