# Generated by Django 6.0.4 on 2026-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='course_notes/'),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
