# Generated by Django 6.0.4 on 2026-07-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursenote_attachment_alter_coursenote_content'),
        ('users', '0009_drop_old_student_faculte_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.professor'),
        ),
    ]
