# Generated by Django 6.0.4 on 2026-08-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_professeur'),
        ('users', '0009_drop_old_student_faculte_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.faculty'),
        ),
    ]
