# Generated by Django 6.0.4 on 2026-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_faculte'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promotions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
