# Generated by Django 6.0.3 on 2026-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_file_alter_chatmessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Nouvelle conversation', max_length=100),
        ),
    ]
