# Generated by Django 6.0.4 on 2026-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_coursedocument_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
