# Generated by Django 6.0.3 on 2026-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_admin_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('code', models.CharField(choices=[('droit', 'Droit'), ('sciences_economiques', 'Sciences Économiques'), ('sciences_informatique_ia', 'Sciences Informatique et Intelligence Artificielle'), ('sciences_info_comm', "Sciences d'Information et Communication"), ('theologie', 'Théologie'), ('medecine', 'Médecine'), ('istm', 'ISTM')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('doyen', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculté',
                'verbose_name_plural': 'Facultés',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='admincentral',
            options={'permissions': [('manage_system', 'Peut gérer le système'), ('manage_admin_gestionnaires', 'Peut créer/modifier les admins gestionnaires'), ('supervise_platform', 'Peut superviser la plateforme'), ('manage_security', 'Peut gérer la sécurité'), ('manage_settings', 'Peut gérer les paramètres généraux')], 'verbose_name': 'Admin Central', 'verbose_name_plural': 'Admins Centraux'},
        ),
        migrations.AlterModelOptions(
            name='admingestionnaire',
            options={'permissions': [('manage_secretaires', 'Peut créer/modifier/supprimer les secrétaires'), ('manage_faculty_info', 'Peut gérer les informations des facultés'), ('manage_user_follow_up', 'Peut gérer le suivi administratif')], 'verbose_name': 'Admin Gestionnaire', 'verbose_name_plural': 'Admins Gestionnaires'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': [('add_course_content', 'Peut ajouter les cours'), ('modify_academic_content', 'Peut modifier les contenus académiques'), ('update_teaching_info', "Peut mettre à jour les informations d'enseignement"), ('enrich_knowledge_base', 'Peut enrichir la base de connaissances')], 'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
        migrations.AlterModelOptions(
            name='secretairefacultaire',
            options={'permissions': [('manage_professors', 'Peut gérer les informations des professeurs'), ('register_professors', 'Peut enregistrer les enseignants'), ('update_professor_data', 'Peut mettre à jour les données des professeurs'), ('manage_academic_tasks', 'Peut gérer les tâches administratives académiques')], 'verbose_name': 'Secrétaire Facultaire', 'verbose_name_plural': 'Secrétaires Facultaires'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('interact_with_chatbot', 'Peut interagir avec le chatbot'), ('ask_academic_questions', 'Peut poser des questions académiques'), ('access_learning_resources', 'Peut accéder aux ressources pédagogiques'), ('receive_automated_assistance', 'Peut recevoir une assistance automatisée')], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='admincentral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='admingestionnaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='secretairefacultaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
