# Generated by Django 6.0.3 on 2026-06-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_faculty_alter_admincentral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingestionnaire',
            name='admin_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestionnaires_geres', to='users.admincentral'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professeurs', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='secretairefacultaire',
            name='admin_gestionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretaires_geres', to='users.admingestionnaire'),
        ),
        migrations.AlterField(
            model_name='secretairefacultaire',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretaires', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
