# Generated by Django 6.0.4 on 2026-08-21 13:01 (manually modified to handle existing empty matricules)

from django.db import migrations, models
import random


def assign_unique_matricules(apps, schema_editor):
    """
    Attribue un matricule unique aux étudiants qui n'en ont pas
    (ceux créés avant que le champ devienne obligatoire).
    Format : LEGACY-<id>-<random>
    """
    Student = apps.get_model('users', 'Student')
    students_without_matricule = Student.objects.filter(matricule='')
    used_matricules = set(
        Student.objects.exclude(matricule='').values_list('matricule', flat=True)
    )

    for student in students_without_matricule:
        while True:
            candidate = f"LEGACY-{student.id}-{random.randint(1000, 9999)}"
            if candidate not in used_matricules:
                used_matricules.add(candidate)
                student.matricule = candidate
                student.save(update_fields=['matricule'])
                break


def reverse_assign_matricules(apps, schema_editor):
    """Rend les matricules LEGACY vides à nouveau (pour rollback)."""
    Student = apps.get_model('users', 'Student')
    Student.objects.filter(matricule__startswith='LEGACY-').update(matricule='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_drop_old_student_faculte_column'),
    ]

    operations = [
        # 1. Ajouter les nouveaux champs (sans contrainte unique sur matricule pour l'instant)
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        # 2. Remplir les matricules vides AVANT d'appliquer unique=True
        migrations.RunPython(
            assign_unique_matricules,
            reverse_code=reverse_assign_matricules,
        ),
        # 3. Maintenant appliquer la contrainte unique (toutes les valeurs sont non-vides et uniques)
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
