# Generated by Django 6.0.4 on 2026-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_import_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': [('add_course_content', 'Peut ajouter les cours'), ('modify_academic_content', 'Peut modifier les contenus académiques'), ('update_teaching_info', "Peut mettre à jour les informations d'enseignement"), ('enrich_knowledge_base', 'Peut enrichir la base de connaissances')], 'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='secretairefacultaire',
            options={'permissions': [('manage_professors', 'Peut gérer les informations des enseignants'), ('register_professors', 'Peut enregistrer les enseignants'), ('update_professor_data', 'Peut mettre à jour les données des enseignants'), ('manage_academic_tasks', 'Peut gérer les tâches administratives académiques')], 'verbose_name': 'Secrétaire Facultaire', 'verbose_name_plural': 'Secrétaires Facultaires'},
        ),
        migrations.AddField(
            model_name='professor',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='postnom',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='professor',
            name='prenom',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='professor',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='postnom',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='prenom',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nom',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=25),
        ),
    ]
